package swresample

//#include <libavutil/samplefmt.h>
import "C"

const (
	AV_SAMPLE_FMT_NONE = C.AV_SAMPLE_FMT_NONE
	AV_SAMPLE_FMT_U8   = C.AV_SAMPLE_FMT_U8
	AV_SAMPLE_FMT_S16  = C.AV_SAMPLE_FMT_S16
	AV_SAMPLE_FMT_S32  = C.AV_SAMPLE_FMT_S32
	AV_SAMPLE_FMT_FLT  = C.AV_SAMPLE_FMT_FLT
	AV_SAMPLE_FMT_DBL  = C.AV_SAMPLE_FMT_DBL
)
